use-sort:
    group:
        - _main
        - SeoTracker
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /**
     * This file is part of the Seo Core package
     *
     * Copyright (c) 2014 Mickaël Andrieu
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     */
